Update master_3.yml

diff --git a/.github/workflows/master_3.yml b/.github/workflows/master_3.yml
--- a/.github/workflows/master_3.yml
+++ b/.github/workflows/master_3.yml
@@ -115,15 +115,15 @@ jobs:
 
           if [[ "${{ env.BRANCH }}" != "qa" && "${{ env.BRANCH }}" != "main" && "${{ env.ENV }}" == "qa" ]]; then
             echo "QA environment can only be deployed from the 'qa' or 'main' branch."
-            exit 1
+            exit 1;
           fi
 
-      - name: Validate Function Name
+      - name: Validate Function Name 
         run: |
-          if [[ -z "${{ env.FUNCTION_NAME }}" ]]; then
-            echo "Data source (function_name) cannot be empty."
-            exit 1
-          fi
+          if [[ -z "${{ env.FUNCTION_NAME }}" ]]; then 
+            echo "Data source (function_name) cannot be empty." 
+            exit 1 
+          fi 
 
       - name: Validate Deployment Inputs 
         run: |
@@ -158,45 +158,45 @@ jobs:
         if: ${{ inputs.databricks_deployment_steps != 'none' }} 
         run: | 
           curl -X POST \ 
-            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \ 
+            -H "Authorization : Bearer ${{ secrets.GITHUB_TOKEN }}" \ 
             -d '{"ref": "refs/heads/${{ env.BRANCH }}", "inputs": {"environment": "${{ env.ENV }}", "date": "${{ inputs.date }}", "databricks_deployment_steps": "${{ inputs.databricks_deployment_steps }}", "function_name": "${{ env.FUNCTION_NAME }}"}}' \ 
             https://api.github.com/repos/${{ github.repository }}/actions/workflows/databricks.yml/dispatches 
 
       # Trigger ADF Pipelines Deployment 
-      - name: Trigger ADF Pipelines Deployment 
-        if: ${{ inputs.adf_pipelines_deployment_steps != 'none' }} 
-        run: | 
-          curl -X POST \ 
-            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \ 
-            -d '{"ref": "refs/heads/${{ env.BRANCH }}", "inputs": {"environment": "${{ env.ENV }}", "date": "${{ inputs.date }}", "adf_pipelines_deployment_steps": "${{ inputs.adf_pipelines_deployment_steps }}", "function_name": "${{ env.FUNCTION_NAME }}"}}' \ 
-            https://api.github.com/repos/${{ github.repository }}/actions/workflows/adf_pipelines.yml/dispatches 
+      - name : Trigger ADF Pipelines Deployment 
+        if : ${{ inputs.adf_pipelines_deployment_steps != 'none' }} 
+        run : |  
+           curl -X POST \  
+             -H “Authorization : Bearer ${{ secrets.GITHUB_TOKEN }}” \  
+             -d '{"ref": “refs/heads/${ {env.BRANCH}}”, “inputs”: {“environment”: “${ {env.ENV}}”, “date”: “${ {inputs.date}}”, “function_name”: “${ {env.FUNCTION_NAME}}”}}’ \  
+             https://api.github.com/repos/${ {github.repository}}/actions/workflows/adf_pipelines.yml/dispatches 
 
       # Trigger ADF Linked Services Deployment 
-      - name: Trigger ADF Linked Services Deployment 
-        if: ${{ inputs.deploy_linked_service == true }} 
-        run: | 
-          curl -X POST \ 
-            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \ 
-            -d '{"ref": "refs/heads/${{ env.BRANCH }}", "inputs": {"environment": "${{ env.ENV }}", "date": "${{ inputs.date }}", "function_name": "${{ env.FUNCTION_NAME }}"}}' \ 
-            https://api.github.com/repos/${{ github.repository }}/actions/workflows/adf_linked_service.yml/dispatches 
+      - name : Trigger ADF Linked Services Deployment 
+         if : ${{ inputs.deploy_linked_service == true }}  
+         run : |  
+           curl -X POST \  
+             -H “Authorization : Bearer ${{ secrets.GITHUB_TOKEN }}” \  
+             -d '{"ref": “refs/heads/${ {env.BRANCH}}”, “inputs”: {“environment”: “${ {env.ENV}}”, “date”: “${ {inputs.date}}”, “function_name”: “${ {env.FUNCTION_NAME}}”}}’ \  
+             https://api.github.com/repos/${ {github.repository}}/actions/workflows/adf_linked_service.yml/dispatches 
 
       # Trigger ADF Datasets Deployment 
-      - name: Trigger ADF Datasets Deployment 
-        if: ${{ inputs.deploy_datasets == true }} 
-        run: | 
-          curl -X POST \ 
-            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \ 
-            -d '{"ref": "refs/heads/${{ env.BRANCH }}", "inputs": {"environment": "${{ env.ENV }}", "date": "${{ inputs.date }}", "function_name": "${{ env.FUNCTION_NAME }}"}}' \ 
-            https://api.github.com/repos/${{ github.repository }}/actions/workflows/adf_dataset.yml/dispatches 
+      - name : Trigger ADF Datasets Deployment 
+         if : ${{ inputs.deploy_datasets == true }}  
+         run : |  
+           curl -X POST \  
+             -H “Authorization : Bearer ${{ secrets.GITHUB_TOKEN }}” \  
+             -d '{"ref": “refs/heads/${ {env.BRANCH}}”, “inputs”: {“environment”: “${ {env.ENV}}”, “date”: “${ {inputs.date}}”, “function_name”: “${ {env.FUNCTION_NAME}}”}}’ \  
+             https://api.github.com/repos/${ {github.repository}}/actions/workflows/adf_dataset.yml/dispatches 
 
       # Trigger ADF Triggers Deployment 
-      - name: Trigger ADF Triggers Deployment 
-        if: ${{ inputs.deploy_triggers == true }} 
-        run: |  
+      - name : Trigger ADF Triggers Deployment 
+         if : ${{ inputs.deploy_triggers == true }}  
+         run : |  
            curl -X POST \  
-             -H "Authorization : Bearer ${{ secrets.GITHUB_TOKEN }}" \  
-             -d '{"ref": "refs/heads/${{ env.BRANCH }}", "inputs": {"environment": "${{ env.ENV }}", "date": "${{ inputs.date }}", "function_name": "${{ env.FUNCTION_NAME }}"}}' \  
-             https://api.github.com/repos/${{ github.repository }}/actions/workflows/adf_trigger.yml/dispatches 
+             -H “Authorization : Bearer ${{ secrets.GITHUB_TOKEN }}” \  
+             -d '{"ref": “refs/heads/${ {env.BRANCH}}”, “inputs”: {“environment”: “${ {env.ENV}}”, “date”: “${ {inputs.date}}”, “function_name”: “${ {env.FUNCTION_NAME}}”}}’ \  
+             https://api.github.com/repos/${ {github.repository}}/actions/workflows/adf_trigger.yml/dispatches 
 
        # Trigger ADF Dataflows Deployment  
        - name : Trigger ADF Dataflows Deployment  
@@ -205,5 +205,5 @@ jobs:
            curl -X POST \  
              -H “Authorization : Bearer ${{ secrets.GITHUB_TOKEN }}” \  
              -d '{"ref": “refs/heads/${ {env.BRANCH}}”, “inputs”: {“environment”: “${ {env.ENV}}”, “date”: “${ {inputs.date}}”, “function_name”: “${ {env.FUNCTION_NAME}}”}}’ \  
-             https://api.github.com/repos/${ {github.repository}}/actions/workflows/adf_dataflows.yml/dispatches
+             https://api.github.com/repos/${ {github.repository}}/actions/workflows/adf_dataflows.yml/dispatches 
 
