Update master_3.yml

diff --git a/.github/workflows/master_3.yml b/.github/workflows/master_3.yml
--- a/.github/workflows/master_3.yml
+++ b/.github/workflows/master_3.yml
@@ -3,6 +3,11 @@ name: Master Deployment Workflow_3
 on:
   workflow_dispatch:
     inputs:
+      branch:
+        description: 'Select the branch to deploy (e.g., main, develop, qa)'
+        type: string
+        required: true
+        default: ''  # Default value is blank, user can provide a branch name like main, develop, or qa.
       environment:
         description: 'Environment to deploy'
         type: choice
@@ -12,30 +17,36 @@ on:
           - prod
         required: true
       function_name:
-        description: 'Select Data Source to deploy'
-        type: choice
-        options:
-          - none
-          - all
-          - IQVIA_SALES
-          - SA_INSIGHTS
-          - MPB-MNC
-          - SFDC_CRM
-          - VARICENT_SALES
+        description: "Please enter the data source to deploy (this should be the project folder name located under the 'data products' folder) - Example: \"MPB-MNC, SA_INSIGHTS\""
+        type: string
         required: true
-      databricks_deployment:
-        description: 'Enable Databricks Deployment?'
-        type: boolean
+      date:
+        description: 'Deploy changes after a commit date in YYYY-MM-DD format (OPTIONAL)'
+        type: string
+        default: '1999-01-01'
         required: true
       databricks_deployment_steps:
         description: 'Select Databricks deployment step'
         type: choice
         options:
           - none
-          - ingestion_utilities
           - ddl
           - dml
           - all
+        required: false
+        default: 'none'
+      adf_pipelines_deployment_steps:
+        description: 'Select ADF Pipelines deployment step'
+        type: choice
+        options:
+          - none
+          - all
+          - landing
+          - bronze
+          - silver
+          - gold
+          - master
+          - miscellaneous
         required: false
         default: 'none'
       deploy_linked_service:
@@ -46,30 +57,15 @@ on:
         description: 'Deploy ADF Datasets'
         type: boolean
         required: false
-      deploy_common_pipelines:
-        description: 'Deploy ADF Common Pipelines'
-        type: choice
-        options:
-            - bronze
-            - gold
-            - landing
-            - master
-            - miscellaneous
-            - silver
-        required: false    
       deploy_triggers:
         description: 'Deploy ADF Triggers'
         type: boolean
         required: false
-      date:
-        description: 'Deploy changes after a commit date in YYYY-MM-DD format (OPTIONAL)'
-        type: string
-        default: '1999-01-01'
-        required: true
 
 env:
   ENVIRONMENT: ${{ inputs.environment }}
   DATE: ${{ inputs.date }}
+  BRANCH: ${{ inputs.branch }}
 
 jobs:
   validate_inputs:
@@ -81,40 +77,80 @@ jobs:
             echo "Invalid date format. Please use YYYY-MM-DD."
             exit 1
           fi
-          
+      
       - name: Validate Future Date
         run: |
           if [[ "${{ inputs.date }}" > "$(date +%Y-%m-%d)" ]]; then
             echo "The specified date is in the future. Please provide a valid past date."
             exit 1
           fi
+      
+      - name: Validate Environment Selection
+        run: |
+          if [[ -z "${{ inputs.environment }}" ]]; then
+            echo "Environment selection cannot be empty."
+            exit 1
+          fi
+      
+      - name: Validate Function Name
+        run: |
+          if [[ -z "${{ inputs.function_name }}" ]]; then
+            echo "Data source (function_name) cannot be empty."
+            exit 1
+          fi
+      
+      - name: Validate Linked Services and Datasets Deployment
+        run: |
+          if [[ "${{ inputs.deploy_linked_service }}" == "true" || "${{ inputs.deploy_datasets }}" == "true" ]]; then
+            if [[ "${{ inputs.function_name }}" == "none" ]]; then
+              echo "If deploying linked services or datasets, a valid function name must be provided."
+              exit 1
+            fi
+          fi
 
-  approval_gate:
-    if: ${{ inputs.environment == 'prod' && github.ref == 'refs/heads/main' }}
-    runs-on: ubuntu-latest
-    environment:
-      name: prod
-      url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
-    steps:
-      - name: Await Approval for Production Deployment
-        run: echo "Waiting for admin approval to proceed with production deployment."
+      - name: Validate Environment Based on Branch
+        run: |
+          if [[ "${{ inputs.environment }}" == "prod" && "${{ inputs.branch }}" != "main" ]]; then
+            echo "Production environment ('prod') can only be deployed from the 'main' branch."
+            exit 1
+          fi
+          if [[ "${{ inputs.environment }}" == "qat" && "${{ inputs.branch }}" != "qat" && "${{ inputs.branch }}" != "main" ]]; then
+            echo "QA environment ('qat') can only be deployed from the 'qat' or 'main' branch."
+            exit 1
+          fi
+          if [[ "${{ inputs.environment }}" == "dev" ]]; then
+            echo "All branches can deploy to the 'dev' environment."
+          else
+            echo "Invalid combination of branch '${{ inputs.branch }}' and environment '${{ inputs.environment }}'."
+            exit 1
+          fi
 
   trigger_workflows:
     name: Trigger Deployment Workflows
     runs-on: ubuntu-latest
-    needs: [validate_inputs, approval_gate]
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v2
+        with:
+          ref: ${{ inputs.branch }}  # Checkout the specified branch for the deployment
 
       # Trigger Databricks Deployment
       - name: Trigger Databricks Deployment
-        if: ${{ inputs.databricks_deployment == true }}
+        if: ${{ inputs.databricks_deployment_steps != 'none' }}
         run: |
           curl -X POST \
             -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-            -d '{"ref": "refs/heads/main", "inputs": {"environment": "${{ inputs.environment }}", "date": "${{ inputs.date }}", "databricks_deployment_steps": "${{ inputs.databricks_deployment_steps }}", "function_name": "${{ inputs.function_name }}"}}' \
+            -d '{"ref": "refs/heads/${{ inputs.branch }}", "inputs": {"environment": "${{ inputs.environment }}", "date": "${{ inputs.date }}", "databricks_deployment_steps": "${{ inputs.databricks_deployment_steps }}", "function_name": "${{ inputs.function_name }}"}}' \
             https://api.github.com/repos/${{ github.repository }}/actions/workflows/databricks.yml/dispatches
+
+      # Trigger ADF Pipelines Deployment
+      - name: Trigger ADF Pipelines Deployment
+        if: ${{ inputs.adf_pipelines_deployment_steps != 'none' }}
+        run: |
+          curl -X POST \
+            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+            -d '{"ref": "refs/heads/${{ inputs.branch }}", "inputs": {"environment": "${{ inputs.environment }}", "date": "${{ inputs.date }}", "adf_pipelines_deployment_steps": "${{ inputs.adf_pipelines_deployment_steps }}"}}' \
+            https://api.github.com/repos/${{ github.repository }}/actions/workflows/adf_pipelines.yml/dispatches
 
       # Trigger ADF Datasets Deployment
       - name: Trigger ADF Datasets Deployment
@@ -122,7 +158,7 @@ jobs:
         run: |
           curl -X POST \
             -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-            -d '{"ref": "refs/heads/main", "inputs": {"environment": "${{ inputs.environment }}", "date": "${{ inputs.date }}"}}' \
+            -d '{"ref": "refs/heads/${{ inputs.branch }}", "inputs": {"environment": "${{ inputs.environment }}", "date": "${{ inputs.date }}"}}' \
             https://api.github.com/repos/${{ github.repository }}/actions/workflows/adf_dataset.yml/dispatches
 
       # Trigger ADF Linked Services Deployment
@@ -131,17 +167,8 @@ jobs:
         run: |
           curl -X POST \
             -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-            -d '{"ref": "refs/heads/main", "inputs": {"environment": "${{ inputs.environment }}", "date": "${{ inputs.date }}"}}' \
+            -d '{"ref": "refs/heads/${{ inputs.branch }}", "inputs": {"environment": "${{ inputs.environment }}", "date": "${{ inputs.date }}"}}' \
             https://api.github.com/repos/${{ github.repository }}/actions/workflows/adf_linked_service.yml/dispatches
-
-      # Trigger ADF Common Pipelines Deployment
-      - name: Trigger ADF Common Pipelines Deployment
-        if: ${{ inputs.deploy_common_pipelines == true }}
-        run: |
-          curl -X POST \
-            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-            -d '{"ref": "refs/heads/main", "inputs": {"environment": "${{ inputs.environment }}", "date": "${{ inputs.date }}"}}' \
-            https://api.github.com/repos/${{ github.repository }}/actions/workflows/adf_common_pipelines.yml/dispatches
 
       # Trigger ADF Triggers Deployment
       - name: Trigger ADF Triggers Deployment
@@ -149,5 +176,5 @@ jobs:
         run: |
           curl -X POST \
             -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-            -d '{"ref": "refs/heads/main", "inputs": {"environment": "${{ inputs.environment }}", "date": "${{ inputs.date }}"}}' \
+            -d '{"ref": "refs/heads/${{ inputs.branch }}", "inputs": {"environment": "${{ inputs.environment }}", "date": "${{ inputs.date }}"}}' \
             https://api.github.com/repos/${{ github.repository }}/actions/workflows/adf_triggers.yml/dispatches
